### ISSUE TITLE
Auto Arima

### ISSUE THREAD

**Issue by Sinansi** [joefowler/ARMA.jl#12]
Hello Joe,

I am switching from Python to Julia.
I am searching for a function that does the same task as Auto Arima in Python (pmdarima) and R (forecast).

Is your model_selection.jl code meant to do the same task? 
And can I use it on Julia 1.2?

Thank you!

**Comment by joefowler** [comment]
I am not very impressed with how well model_selection.jl works, but yes, it is certainly _meant_ to do the same task. Sorry that I didn't see this question back in November.

**Comment by Sinansi** [comment]
@joefowler Thanks for your reply :) I am already using the package. Keep up the good work.
